# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'kie-server'

    scrape_interval: 10s

    metrics_path: /services/rest/metrics

    basic_auth:
      username: 'admin'
      password: 'admin'

    static_configs:
      - targets: ['kieserver:8080']